version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    assignees:
      - ivy-lli
  - package-ecosystem: maven
    directory: maven-config
    schedule:
      interval: daily
    assignees:
      - ivy-lli
